/**
 * @license
 * PEI FACILE — CTE-FIX-02S Integration Test Suite
 * Runtime Integration of Semantic Reverse Engineering
 * Baseline Ministerial ↔ Acquired Model ↔ Real Compiled PEI
 */

import { describe, it, expect } from 'vitest';
import { reverseEngineerSchema } from '../core/semanticReverseEngineering';
import { classifyDocumentModel } from '../core/semanticAcquisitionEngine';
import { restorePeiDocumentBinaries } from '../App';
import type { TemplateSchema } from '../core/templateSchemaTypes';
import type { PeiDocument } from '../types/pei';

describe('CTE-FIX-02S — Semantic Calibration Runtime Integration Suite', () => {
  const mockBaseline: TemplateSchema = {
    schemaId: 'SCHEMA_MINISTERIAL_A1',
    templateId: 'A1',
    sourceSha256: 'baseline-sha256',
    sourcePdfFileName: 'baseline.pdf',
    version: '1.0.0',
    schoolOrder: 'A1',
    totalPages: 12,
    pages: [{ pageNumber: 1, widthPt: 595, heightPt: 842 }],
    fields: [
      {
        templateFieldId: 'f-01-studente',
        pageNumber: 1,
        geometry: { xPt: 10, yPt: 20, widthPt: 100, heightPt: 30 },
        label: 'Alunno/a',
        semanticKey: 'studentName',
        fieldType: 'TEXT_SHORT',
        required: true,
        overflowPolicy: 'RIGID',
        status: 'AUTO_VERIFIED',
      },
    ],
    calibrationStatus: 'CALIBRATED',
    geometryValidationStatus: 'PASS',
    visualReviewStatus: 'COMPLETED',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  const mockAcquired: TemplateSchema = {
    schemaId: 'SCHEMA_custom_roma_infanzia',
    templateId: 'model_custom_roma_infanzia',
    sourceSha256: 'custom-sha256',
    sourcePdfFileName: 'custom_roma_infanzia.pdf',
    version: '1.0.0',
    schoolOrder: 'A1',
    totalPages: 1,
    pages: [{ pageNumber: 1, widthPt: 595, heightPt: 842 }],
    fields: [
      {
        templateFieldId: 'field_bambino_local',
        pageNumber: 1,
        geometry: { xPt: 50, yPt: 50, widthPt: 250, heightPt: 22 },
        label: 'BAMBINO/A [INTESTAZIONE]',
        fieldType: 'TEXT_SHORT',
        required: false,
        overflowPolicy: 'RIGID',
        status: 'CANDIDATE',
      },
    ],
    calibrationStatus: 'REVIEW_REQUIRED',
    geometryValidationStatus: 'NOT_RUN',
    visualReviewStatus: 'REQUIRED',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  const mockEvidence: PeiDocument = {
    id: 'doc_evidence_1',
    schoolOrder: 'A1',
    schoolYear: '2025/2026',
    studentCode: 'ALU-REVERSE',
    schoolName: 'Scuola Test',
    classOrSection: 'Sezione A',
    creationDate: new Date().toISOString(),
    lastModifiedDate: new Date().toISOString(),
    values: {
      field_bambino_local: 'ALUNNO TEST CORISPETTIVO',
    },
    fieldStatuses: {},
    notes: {},
  };

  it('TEST A: reverseEngineerSchema is successfully triggered when baseline, custom model, and evidence are provided', () => {
    const { calibratedSchema, diagnostics } = reverseEngineerSchema(
      mockBaseline,
      mockAcquired,
      mockEvidence,
      null
    );

    expect(diagnostics.baselinePresent).toBe(true);
    expect(diagnostics.evidenceSource).toBe('PRESENT');
    expect(calibratedSchema.calibrationStatus).toBe('CALIBRATED');
  });

  it('TEST B: proposals generated by the reverse engineering correctly appear with calculated confidence', () => {
    const { calibratedSchema } = reverseEngineerSchema(
      mockBaseline,
      mockAcquired,
      mockEvidence,
      null
    );

    const childField = calibratedSchema.fields.find((f) => f.templateFieldId === 'field_bambino_local');
    expect(childField).toBeDefined();
    expect(childField!.confidence).toBeGreaterThanOrEqual(95);
    expect(childField!.status).toBe('AUTO_VERIFIED');
  });

  it('TEST C: existing fields are enriched with semantic keys and backgroundMode without creating duplicates', () => {
    const { calibratedSchema } = reverseEngineerSchema(
      mockBaseline,
      mockAcquired,
      mockEvidence,
      null
    );

    const fieldsWithId = calibratedSchema.fields.filter((f) => f.templateFieldId === 'field_bambino_local');
    expect(fieldsWithId.length).toBe(1); // No duplicates
    expect(fieldsWithId[0].semanticKey).toBe('studentName'); // Enriched key
    expect(fieldsWithId[0].backgroundMode).toBe('OPAQUE_WHITE'); // Enriched background mode
  });

  it('TEST D: legacy fallback with absent evidence operates gracefully', () => {
    const { calibratedSchema, diagnostics } = reverseEngineerSchema(
      mockBaseline,
      mockAcquired,
      null, // No evidence document
      null
    );

    expect(calibratedSchema).toBeDefined();
    expect(diagnostics.evidenceSource).toBe('ABSENT');
    const childField = calibratedSchema.fields.find((f) => f.templateFieldId === 'field_bambino_local');
    expect(childField!.semanticKey).toBe('studentName'); // Mapping still succeeds via synonyms
  });

  it('TEST E: absent baseline is handled gracefully without any crash', () => {
    const { calibratedSchema, diagnostics } = reverseEngineerSchema(
      null, // No baseline
      mockAcquired,
      mockEvidence,
      null
    );

    expect(calibratedSchema).toBeDefined();
    expect(diagnostics.baselinePresent).toBe(false);
  });

  it('TEST F: final saved schema contains absolutely no PII/extracted values', () => {
    const { calibratedSchema } = reverseEngineerSchema(
      mockBaseline,
      mockAcquired,
      mockEvidence,
      null
    );

    const serialized = JSON.stringify(calibratedSchema);
    expect(serialized).not.toContain('ALUNNO TEST CORISPETTIVO');
    expect(serialized).not.toContain('ALU-REVERSE');
  });

  it('TEST G: CTE-FIX-02R unit tests remain fully verified and functional', () => {
    const textEvidence = [
      'BAMBINO/A [INTESTAZIONE] GIANNI ROSSI',
    ];
    const { calibratedSchema } = reverseEngineerSchema(mockBaseline, mockAcquired, null, textEvidence);
    const childField = calibratedSchema.fields.find((f) => f.templateFieldId === 'field_bambino_local');
    expect(childField!.fieldType).toBe('TEXT_SHORT');
    expect(childField!.status).toBe('AUTO_VERIFIED');
  });

  it('TEST H: CTE-FIX-02Q (Hierarchical Model Classification) remains unaffected', () => {
    const text = 'PEI scuola infanzia allegato a1 compilato.';
    const result = classifyDocumentModel(text, []);
    expect(result.detectedOrder).toBe('A1');
    expect(result.detectedModelId).toBe('MINISTERIAL_A1');
  });

  it('TEST I: CTE-FIX-02O (Uint8Array Reload Preservation) remains fully functional', () => {
    const bytes = new Uint8Array([5, 4, 3, 2, 1]);
    const doc = {
      sourcePdfBinary: bytes,
      canonicalDocument: bytes,
    };
    const restored = restorePeiDocumentBinaries(doc);
    expect(restored.sourcePdfBinary instanceof Uint8Array).toBe(true);
    expect(restored.canonicalDocument instanceof Uint8Array).toBe(true);
    expect(Array.from(restored.sourcePdfBinary)).toEqual([5, 4, 3, 2, 1]);
  });
});
