/**
 * Canonical Template Engine (CTE) - Release R10
 * Canonical Execution Engine
 *
 * Core Responsibilities:
 * 1. Receives CteDecisionReport, CteActionPlan, and the source PDF document.
 * 2. Fully executes the designated operational plan generated by Release R09 without taking decisions.
 * 3. Handles all 5 standard CteDecision cases deterministically:
 *    - BIND_CANONICAL: direct delivery without modification.
 *    - NORMALIZE_TO_TEMPLATE: executes NormalizationPlanningEngine (R05) & NormalizationExecutionEngine (R06).
 *    - REGISTER_VARIANT: registers new structural variant in CanonicalTemplateRegistry & ClusterRegistry.
 *    - CREATE_NEW_CLUSTER: establishes new cluster family in ClusterRegistry and registers root template.
 *    - REJECT: halts pipeline safely, producing diagnostic rejection report.
 * 4. Yields CanonicalExecutionReport and CanonicalExecutionResult.
 */

import {
  CteDecision,
  CteDecisionReport,
  CteActionPlan,
  CanonicalExecutionResult,
  CanonicalExecutionReport,
  CanonicalExecutionStatus,
  CanonicalExecutionStatistics,
  DocumentAnalysis,
  CanonicalDocumentFingerprint,
  TemplateVersion,
  TemplateCluster,
  NormalizationPlan,
  NormalizedDocument,
} from '../types';
import { NormalizationPlanningEngine } from '../normalization/normalizationPlanningEngine';
import { NormalizationExecutionEngine } from './normalizationExecutionEngine';
import { CanonicalTemplateRegistry, CanonicalTemplateCatalog } from '../catalog';
import { ClusterRegistry } from '../clustering/clusterRegistry';

export interface CanonicalExecutionEngineOptions {
  templateRegistry?: CanonicalTemplateRegistry;
  clusterRegistry?: ClusterRegistry;
  catalog?: CanonicalTemplateCatalog;
  planningEngine?: NormalizationPlanningEngine;
  executionEngine?: NormalizationExecutionEngine;
}

export class CanonicalExecutionEngine {
  private templateRegistry: CanonicalTemplateRegistry;
  private clusterRegistry: ClusterRegistry;
  private catalog: CanonicalTemplateCatalog;
  private planningEngine: NormalizationPlanningEngine;
  private executionEngine: NormalizationExecutionEngine;

  constructor(options?: CanonicalExecutionEngineOptions) {
    this.templateRegistry = options?.templateRegistry || new CanonicalTemplateRegistry();
    this.clusterRegistry = options?.clusterRegistry || new ClusterRegistry();
    this.catalog = options?.catalog || new CanonicalTemplateCatalog(undefined, undefined, this.templateRegistry);
    this.planningEngine = options?.planningEngine || new NormalizationPlanningEngine();
    this.executionEngine = options?.executionEngine || new NormalizationExecutionEngine();
  }

  public getTemplateRegistry(): CanonicalTemplateRegistry {
    return this.templateRegistry;
  }

  public getClusterRegistry(): ClusterRegistry {
    return this.clusterRegistry;
  }

  public getCatalog(): CanonicalTemplateCatalog {
    return this.catalog;
  }

  /**
   * Executes the full operational action plan for the acquired document based on the CteDecisionReport.
   */
  public async execute(params: {
    sourceDocument: ArrayBuffer;
    documentAnalysis: DocumentAnalysis;
    decisionReport: CteDecisionReport;
    actionPlan?: CteActionPlan;
    targetTemplate?: TemplateVersion | null;
    cluster?: TemplateCluster | null;
    phaseTimings?: Record<string, number>;
  }): Promise<CanonicalExecutionResult> {
    const startTime = performance.now();
    const phaseTimings: Record<string, number> = { ...(params.phaseTimings || {}) };
    const execStart = performance.now();

    const decision = params.decisionReport.decision;
    const actionPlan = params.actionPlan || params.decisionReport.actionPlan;
    const fingerprint = params.documentAnalysis.structuralFingerprint;
    const pagesCount = fingerprint.pageCount || params.documentAnalysis.totalPages || 1;

    let canonicalDocument: ArrayBuffer | null = null;
    let finalStatus: CanonicalExecutionStatus = 'success';
    const operationsExecuted: string[] = [];
    const warnings: string[] = [];
    const errors: string[] = [];
    let normalizationReport = undefined;
    let totalTransformations = 0;

    let targetTemplate: TemplateVersion | null = params.targetTemplate || null;
    let cluster: TemplateCluster | null = params.cluster || null;

    // Resolve target template if specified in decision report
    if (!targetTemplate && params.decisionReport.selectedTemplateId) {
      targetTemplate = this.templateRegistry.get(params.decisionReport.selectedTemplateId) || null;
    }

    // Resolve cluster if specified in decision report
    if (!cluster && params.decisionReport.clusterId) {
      cluster = this.clusterRegistry.getCluster(params.decisionReport.clusterId) || null;
    }

    try {
      switch (decision) {
        // -------------------------------------------------------------------
        // 1. BIND_CANONICAL: No modifications, deliver original buffer directly
        // -------------------------------------------------------------------
        case CteDecision.BIND_CANONICAL: {
          canonicalDocument = params.sourceDocument;
          finalStatus = 'success';
          operationsExecuted.push(
            'OPEN_CANONICAL_TEMPLATE: Modello canonico di riferimento caricato con successo.',
            'BIND_DIRECT_LAYOUT: Associazione diretta coordinate/griglia senza trasformazioni geometriche.',
            'HANDOVER_TO_R10: Documento pronto per estrazione strutturata.'
          );
          break;
        }

        // -------------------------------------------------------------------
        // 2. NORMALIZE_TO_TEMPLATE: Plan and execute geometric normalization
        // -------------------------------------------------------------------
        case CteDecision.NORMALIZE_TO_TEMPLATE: {
          operationsExecuted.push('LOAD_TARGET_TEMPLATE: Caricamento geometria modello target.');

          // Generate normalization plan
          const plan: NormalizationPlan = this.planningEngine.createPlan({
            fingerprint,
            geometricAnalysis: params.documentAnalysis.geometricAnalysis,
            targetTemplateId: targetTemplate?.id,
            targetVersion: targetTemplate?.versioneMinisteriale || targetTemplate?.versione,
          });

          operationsExecuted.push(
            `BUILD_NORMALIZATION_PLAN: Pianificate ${plan.totalOperations} operazioni di correzione geometrica.`
          );

          if (plan.requiresNormalization && plan.totalOperations > 0) {
            operationsExecuted.push('PREPARE_NORMALIZATION_EXECUTION: Avvio pipeline esecutiva di trasformazione.');
            const normalizedResult: NormalizedDocument = await this.executionEngine.execute({
              document: params.sourceDocument,
              plan,
              catalog: this.catalog,
              precomputedAnalysisBefore: params.documentAnalysis,
            });

            canonicalDocument = normalizedResult.document;
            normalizationReport = normalizedResult.normalizationReport;
            totalTransformations = normalizedResult.appliedOperations.length;
            finalStatus = 'normalized';
            operationsExecuted.push(
              `HANDOVER_TO_R10: Normalizzazione completata (${totalTransformations} trasformazioni applicate).`
            );
          } else {
            canonicalDocument = params.sourceDocument;
            finalStatus = 'normalized';
            operationsExecuted.push('HANDOVER_TO_R10: Nessuna trasformazione richiesta dal piano.');
          }
          break;
        }

        // -------------------------------------------------------------------
        // 3. REGISTER_VARIANT: Register variant in registries & deliver document
        // -------------------------------------------------------------------
        case CteDecision.REGISTER_VARIANT: {
          const variantId =
            params.decisionReport.sourceTemplateId !== 'ACQUIRED_DOCUMENT'
              ? params.decisionReport.sourceTemplateId
              : `VAR_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;

          operationsExecuted.push('LOCATE_ANCESTOR_CLUSTER: Ricerca cluster di appartenenza.');

          // Ensure cluster exists
          if (!cluster) {
            const clusterId = params.decisionReport.clusterId || `CLUSTER_${variantId}`;
            cluster = this.clusterRegistry.createCluster({
              id: clusterId,
              nome: params.decisionReport.clusterName || `Famiglia ${targetTemplate?.nome || variantId}`,
              descrizione: 'Cluster evolutivo generato automaticamente.',
              ordineScolastico: targetTemplate?.ordineScolastico,
              baseTemplateId: targetTemplate?.id || variantId,
              initialTemplateIds: targetTemplate ? [targetTemplate.id] : [],
            });
          }

          operationsExecuted.push(
            `CREATE_STRUCTURAL_VARIANT_SPEC: Definita nuova variante strutturale ${variantId} per il cluster ${cluster.id}.`
          );

          // Create and register new TemplateVersion
          const newVariantVersion: TemplateVersion = {
            id: variantId,
            nome: `Variante ${targetTemplate?.nome || 'PEI'} (${new Date().toLocaleDateString('it-IT')})`,
            descrizione: 'Variante strutturale registrata dal Canonical Execution Engine R10.',
            ordineScolastico: targetTemplate?.ordineScolastico || 'primaria',
            versioneMinisteriale: targetTemplate?.versioneMinisteriale || 'v_custom',
            versione: 'v_variant',
            annoValidita: new Date().getFullYear(),
            hash: fingerprint.documentStructureHash || `hash_${variantId}`,
            fingerprint: fingerprint,
            geometry: params.documentAnalysis.geometricAnalysis || {
              totalPages: pagesCount,
              overallSkewAngle: 0,
              overallGeometryScore: 95,
              overallConfidence: 0.95,
              pages: [],
              diagnosticSummary: 'Auto generated geometry',
            },
            templateSchema: targetTemplate?.templateSchema || {},
            dataRegistrazione: new Date().toISOString(),
            stato: 'active',
          };

          this.templateRegistry.register(newVariantVersion, { skipDuplicateCheck: true });
          this.clusterRegistry.addTemplateToCluster(cluster.id, variantId);

          operationsExecuted.push(
            `REGISTER_VARIANT_IN_CATALOG: Variante ${variantId} salvata e associata al cluster ${cluster.id}.`,
            'HANDOVER_TO_R10: Documento pronto con variante registrata.'
          );

          canonicalDocument = params.sourceDocument;
          targetTemplate = newVariantVersion;
          finalStatus = 'variant_registered';
          break;
        }

        // -------------------------------------------------------------------
        // 4. CREATE_NEW_CLUSTER: Establish new cluster root & deliver document
        // -------------------------------------------------------------------
        case CteDecision.CREATE_NEW_CLUSTER: {
          const rootTemplateId = `ROOT_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;
          const clusterId = `CLUSTER_${rootTemplateId}`;

          operationsExecuted.push('INITIALIZE_NEW_CLUSTER: Creazione nuova famiglia evolutiva.');

          const rootVersion: TemplateVersion = {
            id: rootTemplateId,
            nome: `Modello Radice ${rootTemplateId}`,
            descrizione: 'Modello capostipite creato automaticamente per nuovo cluster.',
            ordineScolastico: 'primaria',
            versioneMinisteriale: 'v1.0',
            versione: '1.0',
            annoValidita: new Date().getFullYear(),
            hash: fingerprint.documentStructureHash || `hash_${rootTemplateId}`,
            fingerprint: fingerprint,
            geometry: params.documentAnalysis.geometricAnalysis || {
              totalPages: pagesCount,
              overallSkewAngle: 0,
              overallGeometryScore: 90,
              overallConfidence: 0.9,
              pages: [],
              diagnosticSummary: 'New cluster root geometry',
            },
            templateSchema: {},
            dataRegistrazione: new Date().toISOString(),
            stato: 'active',
          };

          this.templateRegistry.register(rootVersion, { skipDuplicateCheck: true });
          cluster = this.clusterRegistry.createCluster({
            id: clusterId,
            nome: `Famiglia ${rootTemplateId}`,
            descrizione: 'Nuovo ceppo di modelli ministeriali/istituzionali.',
            baseTemplateId: rootTemplateId,
            initialTemplateIds: [rootTemplateId],
          });

          operationsExecuted.push(
            `REGISTER_CANONICAL_ROOT_TEMPLATE: Modello capostipite ${rootTemplateId} registrato nel cluster ${clusterId}.`,
            'HANDOVER_TO_R10: Nuovo cluster istituito.'
          );

          canonicalDocument = params.sourceDocument;
          targetTemplate = rootVersion;
          finalStatus = 'cluster_created';
          break;
        }

        // -------------------------------------------------------------------
        // 5. REJECT: Halt pipeline safely
        // -------------------------------------------------------------------
        case CteDecision.REJECT:
        default: {
          canonicalDocument = null;
          finalStatus = 'rejected';
          operationsExecuted.push(
            'HALT_PROCESSING_PIPELINE: Elaborazione interrotta per insufficienza qualitativa o incompatibilità strutturale.',
            'GENERATE_DIAGNOSTIC_REJECTION_REPORT: Emissione report diagnostico di scarto.'
          );
          warnings.push(...params.decisionReport.reasons);
          break;
        }
      }
    } catch (err: unknown) {
      finalStatus = 'failed';
      const errMsg = err instanceof Error ? err.message : String(err);
      errors.push(`Errore critico durante l'esecuzione del piano operativo: ${errMsg}`);
      canonicalDocument = null;
    }

    const execEnd = performance.now();
    phaseTimings.executionMs = Math.round((execEnd - execStart) * 100) / 100;
    const totalDurationMs = Math.round((execEnd - startTime) * 100) / 100;

    // Count total structural boxes in document
    let totalBoxes = 0;
    for (const p of fingerprint.pages || []) {
      totalBoxes += (p.textObjectCount || 0) + (p.vectorObjectCount || 0) + (p.rasterImageCount || 0);
    }

    const statistics: CanonicalExecutionStatistics = {
      totalDurationMs,
      phaseTimings,
      totalPages: pagesCount,
      totalBoxes,
      totalTransformations,
      memoryUsageMb: typeof process !== 'undefined' && process.memoryUsage ? Math.round((process.memoryUsage().heapUsed / 1024 / 1024) * 100) / 100 : undefined,
    };

    const reportId = `EXEC_REP_${decision}_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;
    const now = new Date().toISOString();

    const report: CanonicalExecutionReport = {
      id: reportId,
      executedAt: now,
      decisionExecuted: decision,
      status: finalStatus,
      targetTemplateId: targetTemplate?.id,
      targetTemplateName: targetTemplate?.nome,
      clusterId: cluster?.id,
      clusterName: cluster?.nome,
      operationsExecuted,
      warnings,
      errors,
      statistics,
      normalizationReport,
      decisionReport: params.decisionReport,
      summary: this.buildSummary(decision, finalStatus, totalDurationMs, targetTemplate?.id, cluster?.id),
    };

    return {
      sourceDocument: params.sourceDocument,
      canonicalDocument,
      documentFingerprint: fingerprint,
      templateUsed: targetTemplate,
      cluster,
      decision,
      report,
      statistics,
    };
  }

  private buildSummary(
    decision: CteDecision,
    status: CanonicalExecutionStatus,
    durationMs: number,
    templateId?: string,
    clusterId?: string
  ): string {
    return (
      `Esecuzione CTE completata con stato '${status}' per la decisione ${decision} in ${durationMs.toFixed(1)}ms. ` +
      `Template: ${templateId || 'N/A'}, Cluster: ${clusterId || 'N/A'}.`
    );
  }
}
